import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import { Brain, Target, BookOpen, MessageSquare, TrendingUp, Sparkles, ArrowRight, CheckCircle2 } from "lucide-react";

const features = [
  { icon: Brain, title: "AI Skill Assessment", description: "Smart evaluation of your current level, interests, and learning goals." },
  { icon: Target, title: "Personalized Roadmaps", description: "Custom 3-month learning paths generated by AI, tailored to your pace." },
  { icon: BookOpen, title: "Curated Content", description: "Resources, exercises, and projects for every milestone on your journey." },
  { icon: MessageSquare, title: "AI Mentor Chat", description: "Ask questions, get explanations, and debug code with your AI mentor." },
  { icon: TrendingUp, title: "Progress Tracking", description: "Visual progress dashboard with streaks, completions, and insights." },
  { icon: Sparkles, title: "Smart Projects", description: "AI recommends projects matching your skill level and learning goals." },
];

const LandingPage = () => {
  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative overflow-hidden bg-gradient-hero pt-32 pb-20">
        {/* Decorative elements */}
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="absolute -top-40 -right-40 h-[500px] w-[500px] rounded-full bg-primary/10 blur-3xl" />
          <div className="absolute -bottom-40 -left-40 h-[400px] w-[400px] rounded-full bg-accent/10 blur-3xl" />
        </div>

        <div className="container relative mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="mx-auto max-w-3xl text-center"
          >
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary">
              <Sparkles className="h-4 w-4" /> AI-Powered Learning Platform
            </div>
            <h1 className="mb-6 font-display text-5xl font-bold leading-tight tracking-tight text-primary-foreground md:text-7xl">
              Learn Smarter with{" "}
              <span className="text-gradient-primary">SkillPilot AI</span>
            </h1>
            <p className="mb-10 text-lg text-primary-foreground/70 md:text-xl">
              Your personal AI mentor that creates custom learning roadmaps, 
              tracks your progress, and helps you go from beginner to professional.
            </p>
            <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Link to="/signup">
                <Button variant="hero" size="lg" className="h-14 px-8 text-base">
                  Start Learning Free <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </Link>
              <Link to="/login">
                <Button variant="hero-outline" size="lg" className="h-14 px-8 text-base">
                  I Have an Account
                </Button>
              </Link>
            </div>
          </motion.div>

          {/* Stats */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.3 }}
            className="mx-auto mt-16 grid max-w-2xl grid-cols-3 gap-8 text-center"
          >
            {[
              { label: "Learning Paths", value: "50+" },
              { label: "Active Learners", value: "10K+" },
              { label: "Projects Built", value: "25K+" },
            ].map(s => (
              <div key={s.label}>
                <div className="font-display text-3xl font-bold text-primary-foreground">{s.value}</div>
                <div className="mt-1 text-sm text-primary-foreground/50">{s.label}</div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <div className="mx-auto mb-16 max-w-xl text-center">
            <h2 className="mb-4 font-display text-3xl font-bold md:text-4xl">
              Everything you need to <span className="text-gradient-primary">level up</span>
            </h2>
            <p className="text-muted-foreground">
              SkillPilot AI combines the best of personalized mentorship and structured learning.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="group rounded-2xl border bg-card p-6 shadow-card transition-all hover:shadow-elevated"
              >
                <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-primary">
                  <f.icon className="h-6 w-6 text-primary-foreground" />
                </div>
                <h3 className="mb-2 font-display text-lg font-semibold">{f.title}</h3>
                <p className="text-sm text-muted-foreground">{f.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How it Works */}
      <section className="border-t bg-muted/50 py-24">
        <div className="container mx-auto px-4">
          <h2 className="mb-16 text-center font-display text-3xl font-bold md:text-4xl">
            How it <span className="text-gradient-primary">works</span>
          </h2>
          <div className="mx-auto grid max-w-4xl gap-12 md:grid-cols-3">
            {[
              { step: "01", title: "Take Assessment", desc: "Answer a few questions about your skills, interests, and goals." },
              { step: "02", title: "Get Your Roadmap", desc: "AI generates a personalized 3-month learning path just for you." },
              { step: "03", title: "Learn & Build", desc: "Follow your roadmap, build projects, and chat with your AI mentor." },
            ].map((s, i) => (
              <motion.div
                key={s.step}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="text-center"
              >
                <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-primary font-display text-2xl font-bold text-primary-foreground">
                  {s.step}
                </div>
                <h3 className="mb-2 font-display text-xl font-semibold">{s.title}</h3>
                <p className="text-sm text-muted-foreground">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="mx-auto max-w-3xl rounded-3xl bg-gradient-hero p-12 text-center"
          >
            <h2 className="mb-4 font-display text-3xl font-bold text-primary-foreground md:text-4xl">
              Ready to start your journey?
            </h2>
            <p className="mb-8 text-primary-foreground/70">
              Join thousands of learners who are building their dream careers with AI-powered guidance.
            </p>
            <Link to="/signup">
              <Button variant="hero" size="lg" className="h-14 px-10 text-base">
                Get Started Now <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <div className="mt-6 flex items-center justify-center gap-6 text-sm text-primary-foreground/50">
              <span className="flex items-center gap-1"><CheckCircle2 className="h-4 w-4" /> Free to start</span>
              <span className="flex items-center gap-1"><CheckCircle2 className="h-4 w-4" /> No credit card</span>
              <span className="flex items-center gap-1"><CheckCircle2 className="h-4 w-4" /> AI-powered</span>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t py-8">
        <div className="container mx-auto flex items-center justify-between px-4 text-sm text-muted-foreground">
          <span className="font-display font-semibold">SkillPilot AI</span>
          <span>© 2026 All rights reserved</span>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
